FROM ruby:3.3-slim
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential {{#hasPostgres}}libpq-dev {{/hasPostgres}}{{#hasMysql}}default-libmysqlclient-dev {{/hasMysql}}{{^hasPostgres}}{{^hasMysql}}libsqlite3-dev {{/hasMysql}}{{/hasPostgres}}&& rm -rf /var/lib/apt/lists/*
COPY Gemfile ./
RUN bundle install
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "rails db:create db:migrate; rails server -b 0.0.0.0"]
