FROM elixir:1.16-slim
WORKDIR /app
RUN mix local.hex --force && mix local.rebar --force
COPY mix.exs ./
COPY . .
RUN mix deps.get
EXPOSE 4000
CMD ["sh", "-c", "mix ecto.create && mix ecto.migrate; mix phx.server"]
